Why can't I make a class for a `Try` including what I try and then run that in the `try {}` block? Why is it impractical?               class DBConnectTry extends Try {           TryResponse response[] attempt(TryObject o[]...){          //try to connect to database       }         }      Then in a `try ... catch` I could invoke only the `DBConnectTry.attempt`. Would that improve readability / clarity / modularization or is it not a good idea?